version: 2
project_name: esed

before:
  hooks:
    - rustup default stable
    - rustup target add x86_64-unknown-linux-musl

builds:
  - builder: rust
    ldflags: -s -w
    targets:
      - x86_64-unknown-linux-musl
upx:
  - enabled: true
    compress: best

archives:
- formats: binary

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    maintainer: gitlab.com/pepa65
    formats:
      - deb
      - apk
      - rpm
